import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/card'
import CardsSelector from '../components/cardsSelector'
import IncomeDistribution from '../components/incomeDistribution'
import MonthlyBalance from '../components/monthlyBalance'
import styles from '../styles/Home.module.css'
import TransactionItem from '../components/transactionItem'
import ExpensesDistribution from '../components/expensesDistribution'

const Home: NextPage = () => {

  type Transaction = {
    title: string,
    category: {
        color: string,
        icon: string
    },
    date: string,
    ammount: number
}

  const transaction = [
    {ammount: -200,category: {color: '#65dfc9', icon: 'house'}, date: '12 February 2022 at 15: 16', title: 'Gas'},
    {ammount: 200,category: {color: '#3431c2', icon: 'house'}, date: '12 February 2022 at 15: 16', title: 'Gas'},
    {ammount: -200,category: {color: '#FF2C6B', icon: 'house'}, date: '12 February 2022 at 15: 16', title: 'Gas'},
  ]

  return (
    <div >
      <Head>
        <title>Guap</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='dark:bg-white/10 bg-black/5 md:ml-[130px] md:mr-auto dark:text-white md:grid md:grid-cols-2 md:grid-rows-2 grid-rows-4 min-h-[90vh] mt-16 gap-6 p-8 pb-[300px] md:pb-0 z-10 relative w-[80vw] rounded'>

      
      <section>
        <div className='flex flex-col'>
        <p>Hello, Welcome</p>
        <h1 className='text-3xl'>Munyaradzi</h1>
        </div>
        <div className='dark:bg-white/10 dark:text-white relative p-5 rounded w-[100%] bg-white shadow-md'>
      <h1 className=' text-xl font-bold top-0 left-6'>Your Cards</h1>

      <CardsSelector>
      <Card accountType='Cheque' bank={'fnb'} name='Munyaradzi' number='5555-5555-5555-5555'/>
      <Card accountType='Savings' bank={'absa'} name='Munyaradzi' number='5555-5555-5555-5555'/>
      <Card accountType='Savings' bank={'paypal'} name='Munyaradzi' number='5555-5555-5555-5555'/>
      </CardsSelector>
        </div>
      </section>
      <section>
        <h1 className='text-3xl mt-6'>Distribution</h1>
        <div className='flex w-[100%] justify-between md:flex-row flex-col'>
        <IncomeDistribution/>
        <ExpensesDistribution/>
        </div>
      </section>
      <section>
        <h1 className='text-3xl'>Monthly Balance</h1>
        <MonthlyBalance/>
      </section>
      <section>
        <h1 className='text-3xl'>Recent Transactions</h1>
        {
        transaction.map((x, y) => <TransactionItem key={y} ammount={x.ammount} category={x.category} title={x.title} date={x.date}/>)
      }
      </section>
      </main>

    </div>
  )
}

export default Home
